services:
  - type: web
    name: studio-dub-tycoon-web
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BOT_AUTO_START
        value: "1"
      - key: GAME_USE_DB
        value: "1"
      - key: WEB_CONCURRENCY
        value: "1"
      - key: WEBHOOK_SECRET
        sync: false
      - key: TELEGRAM_SECRET_TOKEN
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: studio-dub-tycoon-web
          property: url
